### ISSUE TITLE
PIP3 does not download the 0.9.0 version of rigid-body-motion

### ISSUE THREAD

**Issue by Andrzej1312** [phausamann/rigid-body-motion#31]
* Rigid Body Motion version: 0.9.0
* Python version: 3.8
* Operating System: Elementary OS

### Description

For some reason, my pip3 does not see the 0.9.0 version of rigid-body-motion. 

### What I Did
With the newest pip3,

when specifying the version explicitly, the following output from pip3 confirms that rgb v 0.9.0 is not "visible".

pip install rigid-body-motion===0.9.0
ERROR: Could not find a version that satisfies the requirement rigid-body-motion===0.9.0 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.3.0, 0.4.0, 0.4.1, 0.5.0, 0.6.0, 0.7.0)
ERROR: No matching distribution found for rigid-body-motion===0.9.0
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
Thanks in advance!

**Comment by phausamann** [comment]
Thanks for the report @Andrzej1312. Can you try `pip install rigid-body-motion==0.9.1`? That should fix it.

**Comment by Andrzej1312** [comment]
Thank you @phausamann, 
using `pip install rigid-body-motion==0.9.1` works as suggested :)
