### ISSUE TITLE
[Google Collab]AttributeError: 'RendererAgg' object has no attribute 'M'

### ISSUE THREAD

**Issue by 17373355** [phausamann/rigid-body-motion#35]
* Rigid Body Motion version: rigid-body-motion 0.9.1
* Python version: Python 3.10.11
* Operating System: 
*DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"

### Description

Download reference_frame and try to run it on Google Collab.

Then this issue occurred when I tried to plot the arrow:
---------------------------------------------------------------
fig = plt.figure()
ax = fig.add_subplot(111, projection="3d")

rbm.plot.reference_frame(rf_world, ax=ax)
rbm.plot.reference_frame(rf_observer, rf_world, ax=ax)

fig.tight_layout()
---------------------------------------------------------------
Error in callback <function _draw_all_if_interactive at 0x7fc3d6e01d80> (for post_execute):
### ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/matplotlib/pyplot.py](https://localhost:8080/#) in _draw_all_if_interactive()
    118 def _draw_all_if_interactive():
    119     if matplotlib.is_interactive():
--> 120         draw_all()
    121 
    122 

13 frames
[/usr/local/lib/python3.10/dist-packages/rigid_body_motion/plotting.py](https://localhost:8080/#) in draw(self, renderer)
     19         """ Draw to the given renderer. """
     20         xs3d, ys3d, zs3d = self._verts3d
---> 21         xs, ys, _ = proj3d.proj_transform(xs3d, ys3d, zs3d)
     22         self.set_positions((xs[0], ys[0]), (xs[1], ys[1]))
     23         FancyArrowPatch.draw(self, renderer)

AttributeError: 'RendererAgg' object has no attribute 'M'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/IPython/core/formatters.py](https://localhost:8080/#) in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

12 frames
[/usr/local/lib/python3.10/dist-packages/rigid_body_motion/plotting.py](https://localhost:8080/#) in draw(self, renderer)
     19         """ Draw to the given renderer. """
     20         xs3d, ys3d, zs3d = self._verts3d
---> 21         xs, ys, _ = proj3d.proj_transform(xs3d, ys3d, zs3d)
     22         self.set_positions((xs[0], ys[0]), (xs[1], ys[1]))
     23         FancyArrowPatch.draw(self, renderer)

AttributeError: 'RendererAgg' object has no attribute 'M'
<Figure size 600x600 with 1 Axes>

### What I Did
All I add is 
!pip install rigid-body-motion
```

```

**Comment by EmmanuelMess** [comment]
Please create a release with this fix.

**Comment by phausamann** [comment]
@EmmanuelMess sorry about that. Had to work out some build issues. Release is published now.
